<?php

return [

	[
		'639-1' => 'ab',
		'639-2/t' => 'abk',
		'639-2/b' => 'abk',
		'639-3' => 'abk',
		'iso_language_name' => 'Abkhaz',
		'native_name_(endonym)' => 'аҧсуа бызшәа, аҧсшәа',
	],
	[
		'639-1' => 'aa',
		'639-2/t' => 'aar',
		'639-2/b' => 'aar',
		'639-3' => 'aar',
		'iso_language_name' => 'Afar',
		'native_name_(endonym)' => 'Afaraf',
	],
	[
		'639-1' => 'af',
		'639-2/t' => 'afr',
		'639-2/b' => 'afr',
		'639-3' => 'afr',
		'iso_language_name' => 'Afrikaans',
		'native_name_(endonym)' => 'Afrikaans',
	],
	[
		'639-1' => 'ak',
		'639-2/t' => 'aka',
		'639-2/b' => 'aka',
		'639-3' => 'aka',
		'iso_language_name' => 'Akan',
		'native_name_(endonym)' => 'Akan',
	],
	[
		'639-1' => 'sq',
		'639-2/t' => 'sqi',
		'639-2/b' => 'alb',
		'639-3' => 'sqi',
		'iso_language_name' => 'Albanian',
		'native_name_(endonym)' => 'Shqip',
	],
	[
		'639-1' => 'am',
		'639-2/t' => 'amh',
		'639-2/b' => 'amh',
		'639-3' => 'amh',
		'iso_language_name' => 'Amharic',
		'native_name_(endonym)' => 'አማርኛ',
	],
	[
		'639-1' => 'ar',
		'639-2/t' => 'ara',
		'639-2/b' => 'ara',
		'639-3' => 'ara',
		'iso_language_name' => 'Arabic',
		'native_name_(endonym)' => 'العربية',
	],
	[
		'639-1' => 'an',
		'639-2/t' => 'arg',
		'639-2/b' => 'arg',
		'639-3' => 'arg',
		'iso_language_name' => 'Aragonese',
		'native_name_(endonym)' => 'aragonés',
	],
	[
		'639-1' => 'hy',
		'639-2/t' => 'hye',
		'639-2/b' => 'arm',
		'639-3' => 'hye',
		'iso_language_name' => 'Armenian',
		'native_name_(endonym)' => 'Հայերեն',
	],
	[
		'639-1' => 'as',
		'639-2/t' => 'asm',
		'639-2/b' => 'asm',
		'639-3' => 'asm',
		'iso_language_name' => 'Assamese',
		'native_name_(endonym)' => 'অসমীয়া',
	],
	[
		'639-1' => 'av',
		'639-2/t' => 'ava',
		'639-2/b' => 'ava',
		'639-3' => 'ava',
		'iso_language_name' => 'Avaric',
		'native_name_(endonym)' => 'авар мацӀ, магӀарул мацӀ',
	],
	[
		'639-1' => 'ae',
		'639-2/t' => 'ave',
		'639-2/b' => 'ave',
		'639-3' => 'ave',
		'iso_language_name' => 'Avestan',
		'native_name_(endonym)' => 'avesta',
	],
	[
		'639-1' => 'ay',
		'639-2/t' => 'aym',
		'639-2/b' => 'aym',
		'639-3' => 'aym',
		'iso_language_name' => 'Aymara',
		'native_name_(endonym)' => 'aymar aru',
	],
	[
		'639-1' => 'az',
		'639-2/t' => 'aze',
		'639-2/b' => 'aze',
		'639-3' => 'aze',
		'iso_language_name' => 'Azerbaijani',
		'native_name_(endonym)' => 'azərbaycan dili',
	],
	[
		'639-1' => 'bm',
		'639-2/t' => 'bam',
		'639-2/b' => 'bam',
		'639-3' => 'bam',
		'iso_language_name' => 'Bambara',
		'native_name_(endonym)' => 'bamanankan',
	],
	[
		'639-1' => 'ba',
		'639-2/t' => 'bak',
		'639-2/b' => 'bak',
		'639-3' => 'bak',
		'iso_language_name' => 'Bashkir',
		'native_name_(endonym)' => 'башҡорт теле',
	],
	[
		'639-1' => 'eu',
		'639-2/t' => 'eus',
		'639-2/b' => 'baq',
		'639-3' => 'eus',
		'iso_language_name' => 'Basque',
		'native_name_(endonym)' => 'euskara, euskera',
	],
	[
		'639-1' => 'be',
		'639-2/t' => 'bel',
		'639-2/b' => 'bel',
		'639-3' => 'bel',
		'iso_language_name' => 'Belarusian',
		'native_name_(endonym)' => 'беларуская мова',
	],
	[
		'639-1' => 'bn',
		'639-2/t' => 'ben',
		'639-2/b' => 'ben',
		'639-3' => 'ben',
		'iso_language_name' => 'Bengali, Bangla',
		'native_name_(endonym)' => 'বাংলা',
	],
	[
		'639-1' => 'bh',
		'639-2/t' => 'bih',
		'639-2/b' => 'bih',
		'639-3' => '',
		'iso_language_name' => 'Bihari',
		'native_name_(endonym)' => 'भोजपुरी',
	],
	[
		'639-1' => 'bi',
		'639-2/t' => 'bis',
		'639-2/b' => 'bis',
		'639-3' => 'bis',
		'iso_language_name' => 'Bislama',
		'native_name_(endonym)' => 'Bislama',
	],
	[
		'639-1' => 'bs',
		'639-2/t' => 'bos',
		'639-2/b' => 'bos',
		'639-3' => 'bos',
		'iso_language_name' => 'Bosnian',
		'native_name_(endonym)' => 'bosanski jezik',
	],
	[
		'639-1' => 'br',
		'639-2/t' => 'bre',
		'639-2/b' => 'bre',
		'639-3' => 'bre',
		'iso_language_name' => 'Breton',
		'native_name_(endonym)' => 'brezhoneg',
	],
	[
		'639-1' => 'bg',
		'639-2/t' => 'bul',
		'639-2/b' => 'bul',
		'639-3' => 'bul',
		'iso_language_name' => 'Bulgarian',
		'native_name_(endonym)' => 'български език',
	],
	[
		'639-1' => 'my',
		'639-2/t' => 'mya',
		'639-2/b' => 'bur',
		'639-3' => 'mya',
		'iso_language_name' => 'Burmese',
		'native_name_(endonym)' => 'ဗမာစာ',
	],
	[
		'639-1' => 'ca',
		'639-2/t' => 'cat',
		'639-2/b' => 'cat',
		'639-3' => 'cat',
		'iso_language_name' => 'Catalan',
		'native_name_(endonym)' => 'català',
	],
	[
		'639-1' => 'ch',
		'639-2/t' => 'cha',
		'639-2/b' => 'cha',
		'639-3' => 'cha',
		'iso_language_name' => 'Chamorro',
		'native_name_(endonym)' => 'Chamoru',
	],
	[
		'639-1' => 'ce',
		'639-2/t' => 'che',
		'639-2/b' => 'che',
		'639-3' => 'che',
		'iso_language_name' => 'Chechen',
		'native_name_(endonym)' => 'нохчийн мотт',
	],
	[
		'639-1' => 'ny',
		'639-2/t' => 'nya',
		'639-2/b' => 'nya',
		'639-3' => 'nya',
		'iso_language_name' => 'Chichewa, Chewa, Nyanja',
		'native_name_(endonym)' => 'chiCheŵa, chinyanja',
	],
	[
		'639-1' => 'zh',
		'639-2/t' => 'zho',
		'639-2/b' => 'chi',
		'639-3' => 'zho',
		'iso_language_name' => 'Chinese',
		'native_name_(endonym)' => '中文 (Zhōngwén), 汉语, 漢語',
	],
	[
		'639-1' => 'cv',
		'639-2/t' => 'chv',
		'639-2/b' => 'chv',
		'639-3' => 'chv',
		'iso_language_name' => 'Chuvash',
		'native_name_(endonym)' => 'чӑваш чӗлхи',
	],
	[
		'639-1' => 'kw',
		'639-2/t' => 'cor',
		'639-2/b' => 'cor',
		'639-3' => 'cor',
		'iso_language_name' => 'Cornish',
		'native_name_(endonym)' => 'Kernewek',
	],
	[
		'639-1' => 'co',
		'639-2/t' => 'cos',
		'639-2/b' => 'cos',
		'639-3' => 'cos',
		'iso_language_name' => 'Corsican',
		'native_name_(endonym)' => 'corsu, lingua corsa',
	],
	[
		'639-1' => 'cr',
		'639-2/t' => 'cre',
		'639-2/b' => 'cre',
		'639-3' => 'cre',
		'iso_language_name' => 'Cree',
		'native_name_(endonym)' => 'ᓀᐦᐃᔭᐍᐏᐣ',
	],
	[
		'639-1' => 'hr',
		'639-2/t' => 'hrv',
		'639-2/b' => 'hrv',
		'639-3' => 'hrv',
		'iso_language_name' => 'Croatian',
		'native_name_(endonym)' => 'hrvatski jezik',
	],
	[
		'639-1' => 'cs',
		'639-2/t' => 'ces',
		'639-2/b' => 'cze',
		'639-3' => 'ces',
		'iso_language_name' => 'Czech',
		'native_name_(endonym)' => 'čeština, český jazyk',
	],
	[
		'639-1' => 'da',
		'639-2/t' => 'dan',
		'639-2/b' => 'dan',
		'639-3' => 'dan',
		'iso_language_name' => 'Danish',
		'native_name_(endonym)' => 'dansk',
	],
	[
		'639-1' => 'dv',
		'639-2/t' => 'div',
		'639-2/b' => 'div',
		'639-3' => 'div',
		'iso_language_name' => 'Divehi, Dhivehi, Maldivian',
		'native_name_(endonym)' => 'ދިވެހި',
	],
	[
		'639-1' => 'nl',
		'639-2/t' => 'nld',
		'639-2/b' => 'dut',
		'639-3' => 'nld',
		'iso_language_name' => 'Dutch',
		'native_name_(endonym)' => 'Nederlands, Vlaams',
	],
	[
		'639-1' => 'dz',
		'639-2/t' => 'dzo',
		'639-2/b' => 'dzo',
		'639-3' => 'dzo',
		'iso_language_name' => 'Dzongkha',
		'native_name_(endonym)' => 'རྫོང་ཁ',
	],
	[
		'639-1' => 'en',
		'639-2/t' => 'eng',
		'639-2/b' => 'eng',
		'639-3' => 'eng',
		'iso_language_name' => 'English',
		'native_name_(endonym)' => 'English',
	],
	[
		'639-1' => 'eo',
		'639-2/t' => 'epo',
		'639-2/b' => 'epo',
		'639-3' => 'epo',
		'iso_language_name' => 'Esperanto',
		'native_name_(endonym)' => 'Esperanto',
	],
	[
		'639-1' => 'et',
		'639-2/t' => 'est',
		'639-2/b' => 'est',
		'639-3' => 'est',
		'iso_language_name' => 'Estonian',
		'native_name_(endonym)' => 'eesti, eesti keel',
	],
	[
		'639-1' => 'ee',
		'639-2/t' => 'ewe',
		'639-2/b' => 'ewe',
		'639-3' => 'ewe',
		'iso_language_name' => 'Ewe',
		'native_name_(endonym)' => 'Eʋegbe',
	],
	[
		'639-1' => 'fo',
		'639-2/t' => 'fao',
		'639-2/b' => 'fao',
		'639-3' => 'fao',
		'iso_language_name' => 'Faroese',
		'native_name_(endonym)' => 'føroyskt',
	],
	[
		'639-1' => 'fj',
		'639-2/t' => 'fij',
		'639-2/b' => 'fij',
		'639-3' => 'fij',
		'iso_language_name' => 'Fijian',
		'native_name_(endonym)' => 'vosa Vakaviti',
	],
	[
		'639-1' => 'fi',
		'639-2/t' => 'fin',
		'639-2/b' => 'fin',
		'639-3' => 'fin',
		'iso_language_name' => 'Finnish',
		'native_name_(endonym)' => 'suomi, suomen kieli',
	],
	[
		'639-1' => 'fr',
		'639-2/t' => 'fra',
		'639-2/b' => 'fre',
		'639-3' => 'fra',
		'iso_language_name' => 'French',
		'native_name_(endonym)' => 'français, langue française',
	],
	[
		'639-1' => 'ff',
		'639-2/t' => 'ful',
		'639-2/b' => 'ful',
		'639-3' => 'ful',
		'iso_language_name' => 'Fula, Fulah, Pulaar, Pular',
		'native_name_(endonym)' => 'Fulfulde, Pulaar, Pular',
	],
	[
		'639-1' => 'gl',
		'639-2/t' => 'glg',
		'639-2/b' => 'glg',
		'639-3' => 'glg',
		'iso_language_name' => 'Galician',
		'native_name_(endonym)' => 'galego',
	],
	[
		'639-1' => 'ka',
		'639-2/t' => 'kat',
		'639-2/b' => 'geo',
		'639-3' => 'kat',
		'iso_language_name' => 'Georgian',
		'native_name_(endonym)' => 'ქართული',
	],
	[
		'639-1' => 'de',
		'639-2/t' => 'deu',
		'639-2/b' => 'ger',
		'639-3' => 'deu',
		'iso_language_name' => 'German',
		'native_name_(endonym)' => 'Deutsch',
	],
	[
		'639-1' => 'el',
		'639-2/t' => 'ell',
		'639-2/b' => 'gre',
		'639-3' => 'ell',
		'iso_language_name' => 'Greek (modern)',
		'native_name_(endonym)' => 'ελληνικά',
	],
	[
		'639-1' => 'gn',
		'639-2/t' => 'grn',
		'639-2/b' => 'grn',
		'639-3' => 'grn',
		'iso_language_name' => 'Guaraní',
		'native_name_(endonym)' => 'Avañe\'ẽ',
	],
	[
		'639-1' => 'gu',
		'639-2/t' => 'guj',
		'639-2/b' => 'guj',
		'639-3' => 'guj',
		'iso_language_name' => 'Gujarati',
		'native_name_(endonym)' => 'ગુજરાતી',
	],
	[
		'639-1' => 'ht',
		'639-2/t' => 'hat',
		'639-2/b' => 'hat',
		'639-3' => 'hat',
		'iso_language_name' => 'Haitian, Haitian Creole',
		'native_name_(endonym)' => 'Kreyòl ayisyen',
	],
	[
		'639-1' => 'ha',
		'639-2/t' => 'hau',
		'639-2/b' => 'hau',
		'639-3' => 'hau',
		'iso_language_name' => 'Hausa',
		'native_name_(endonym)' => '(Hausa) هَوُسَ',
	],
	[
		'639-1' => 'he',
		'639-2/t' => 'heb',
		'639-2/b' => 'heb',
		'639-3' => 'heb',
		'iso_language_name' => 'Hebrew (modern)',
		'native_name_(endonym)' => 'עברית',
	],
	[
		'639-1' => 'hz',
		'639-2/t' => 'her',
		'639-2/b' => 'her',
		'639-3' => 'her',
		'iso_language_name' => 'Herero',
		'native_name_(endonym)' => 'Otjiherero',
	],
	[
		'639-1' => 'hi',
		'639-2/t' => 'hin',
		'639-2/b' => 'hin',
		'639-3' => 'hin',
		'iso_language_name' => 'Hindi',
		'native_name_(endonym)' => 'हिन्दी, हिंदी',
	],
	[
		'639-1' => 'ho',
		'639-2/t' => 'hmo',
		'639-2/b' => 'hmo',
		'639-3' => 'hmo',
		'iso_language_name' => 'Hiri Motu',
		'native_name_(endonym)' => 'Hiri Motu',
	],
	[
		'639-1' => 'hu',
		'639-2/t' => 'hun',
		'639-2/b' => 'hun',
		'639-3' => 'hun',
		'iso_language_name' => 'Hungarian',
		'native_name_(endonym)' => 'magyar',
	],
	[
		'639-1' => 'ia',
		'639-2/t' => 'ina',
		'639-2/b' => 'ina',
		'639-3' => 'ina',
		'iso_language_name' => 'Interlingua',
		'native_name_(endonym)' => 'Interlingua',
	],
	[
		'639-1' => 'id',
		'639-2/t' => 'ind',
		'639-2/b' => 'ind',
		'639-3' => 'ind',
		'iso_language_name' => 'Indonesian',
		'native_name_(endonym)' => 'Bahasa Indonesia',
	],
	[
		'639-1' => 'ie',
		'639-2/t' => 'ile',
		'639-2/b' => 'ile',
		'639-3' => 'ile',
		'iso_language_name' => 'Interlingue',
		'native_name_(endonym)' => 'Originally called Occidental; then Interlingue after WWII',
	],
	[
		'639-1' => 'ga',
		'639-2/t' => 'gle',
		'639-2/b' => 'gle',
		'639-3' => 'gle',
		'iso_language_name' => 'Irish',
		'native_name_(endonym)' => 'Gaeilge',
	],
	[
		'639-1' => 'ig',
		'639-2/t' => 'ibo',
		'639-2/b' => 'ibo',
		'639-3' => 'ibo',
		'iso_language_name' => 'Igbo',
		'native_name_(endonym)' => 'Asụsụ Igbo',
	],
	[
		'639-1' => 'ik',
		'639-2/t' => 'ipk',
		'639-2/b' => 'ipk',
		'639-3' => 'ipk',
		'iso_language_name' => 'Inupiaq',
		'native_name_(endonym)' => 'Iñupiaq, Iñupiatun',
	],
	[
		'639-1' => 'io',
		'639-2/t' => 'ido',
		'639-2/b' => 'ido',
		'639-3' => 'ido',
		'iso_language_name' => 'Ido',
		'native_name_(endonym)' => 'Ido',
	],
	[
		'639-1' => 'is',
		'639-2/t' => 'isl',
		'639-2/b' => 'ice',
		'639-3' => 'isl',
		'iso_language_name' => 'Icelandic',
		'native_name_(endonym)' => 'Íslenska',
	],
	[
		'639-1' => 'it',
		'639-2/t' => 'ita',
		'639-2/b' => 'ita',
		'639-3' => 'ita',
		'iso_language_name' => 'Italian',
		'native_name_(endonym)' => 'italiano',
	],
	[
		'639-1' => 'iu',
		'639-2/t' => 'iku',
		'639-2/b' => 'iku',
		'639-3' => 'iku',
		'iso_language_name' => 'Inuktitut',
		'native_name_(endonym)' => 'ᐃᓄᒃᑎᑐᑦ',
	],
	[
		'639-1' => 'ja',
		'639-2/t' => 'jpn',
		'639-2/b' => 'jpn',
		'639-3' => 'jpn',
		'iso_language_name' => 'Japanese',
		'native_name_(endonym)' => '日本語 (にほんご)',
	],
	[
		'639-1' => 'jv',
		'639-2/t' => 'jav',
		'639-2/b' => 'jav',
		'639-3' => 'jav',
		'iso_language_name' => 'Javanese',
		'native_name_(endonym)' => 'basa Jawa',
	],
	[
		'639-1' => 'kl',
		'639-2/t' => 'kal',
		'639-2/b' => 'kal',
		'639-3' => 'kal',
		'iso_language_name' => 'Kalaallisut, Greenlandic',
		'native_name_(endonym)' => 'kalaallisut, kalaallit oqaasii',
	],
	[
		'639-1' => 'kn',
		'639-2/t' => 'kan',
		'639-2/b' => 'kan',
		'639-3' => 'kan',
		'iso_language_name' => 'Kannada',
		'native_name_(endonym)' => 'ಕನ್ನಡ',
	],
	[
		'639-1' => 'kr',
		'639-2/t' => 'kau',
		'639-2/b' => 'kau',
		'639-3' => 'kau',
		'iso_language_name' => 'Kanuri',
		'native_name_(endonym)' => 'Kanuri',
	],
	[
		'639-1' => 'ks',
		'639-2/t' => 'kas',
		'639-2/b' => 'kas',
		'639-3' => 'kas',
		'iso_language_name' => 'Kashmiri',
		'native_name_(endonym)' => 'कश्मीरी, كشميري‎',
	],
	[
		'639-1' => 'kk',
		'639-2/t' => 'kaz',
		'639-2/b' => 'kaz',
		'639-3' => 'kaz',
		'iso_language_name' => 'Kazakh',
		'native_name_(endonym)' => 'қазақ тілі',
	],
	[
		'639-1' => 'kz',
		'639-2/t' => 'kaz',
		'639-2/b' => 'kaz',
		'639-3' => 'kaz',
		'iso_language_name' => 'Kazakh',
		'native_name_(endonym)' => 'қазақ тілі',
	],
	[
		'639-1' => 'km',
		'639-2/t' => 'khm',
		'639-2/b' => 'khm',
		'639-3' => 'khm',
		'iso_language_name' => 'Khmer',
		'native_name_(endonym)' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ',
	],
	[
		'639-1' => 'ki',
		'639-2/t' => 'kik',
		'639-2/b' => 'kik',
		'639-3' => 'kik',
		'iso_language_name' => 'Kikuyu, Gikuyu',
		'native_name_(endonym)' => 'Gĩkũyũ',
	],
	[
		'639-1' => 'rw',
		'639-2/t' => 'kin',
		'639-2/b' => 'kin',
		'639-3' => 'kin',
		'iso_language_name' => 'Kinyarwanda',
		'native_name_(endonym)' => 'Ikinyarwanda',
	],
	[
		'639-1' => 'ky',
		'639-2/t' => 'kir',
		'639-2/b' => 'kir',
		'639-3' => 'kir',
		'iso_language_name' => 'Kyrgyz',
		'native_name_(endonym)' => 'Кыргызча, Кыргыз тили',
	],
	[
		'639-1' => 'kv',
		'639-2/t' => 'kom',
		'639-2/b' => 'kom',
		'639-3' => 'kom',
		'iso_language_name' => 'Komi',
		'native_name_(endonym)' => 'коми кыв',
	],
	[
		'639-1' => 'kg',
		'639-2/t' => 'kon',
		'639-2/b' => 'kon',
		'639-3' => 'kon',
		'iso_language_name' => 'Kongo',
		'native_name_(endonym)' => 'Kikongo',
	],
	[
		'639-1' => 'ko',
		'639-2/t' => 'kor',
		'639-2/b' => 'kor',
		'639-3' => 'kor',
		'iso_language_name' => 'Korean',
		'native_name_(endonym)' => '한국어, 조선어',
	],
	[
		'639-1' => 'ku',
		'639-2/t' => 'kur',
		'639-2/b' => 'kur',
		'639-3' => 'kur',
		'iso_language_name' => 'Kurdish',
		'native_name_(endonym)' => 'Kurdî, كوردی‎',
	],
	[
		'639-1' => 'kj',
		'639-2/t' => 'kua',
		'639-2/b' => 'kua',
		'639-3' => 'kua',
		'iso_language_name' => 'Kwanyama, Kuanyama',
		'native_name_(endonym)' => 'Kuanyama',
	],
	[
		'639-1' => 'la',
		'639-2/t' => 'lat',
		'639-2/b' => 'lat',
		'639-3' => 'lat',
		'iso_language_name' => 'Latin',
		'native_name_(endonym)' => 'latine, lingua latina',
	],
	[
		'639-1' => '',
		'639-2/t' => '',
		'639-2/b' => '',
		'639-3' => 'lld',
		'iso_language_name' => 'Ladin',
		'native_name_(endonym)' => 'ladin, lingua ladina',
	],
	[
		'639-1' => 'lb',
		'639-2/t' => 'ltz',
		'639-2/b' => 'ltz',
		'639-3' => 'ltz',
		'iso_language_name' => 'Luxembourgish, Letzeburgesch',
		'native_name_(endonym)' => 'Lëtzebuergesch',
	],
	[
		'639-1' => 'lg',
		'639-2/t' => 'lug',
		'639-2/b' => 'lug',
		'639-3' => 'lug',
		'iso_language_name' => 'Ganda',
		'native_name_(endonym)' => 'Luganda',
	],
	[
		'639-1' => 'li',
		'639-2/t' => 'lim',
		'639-2/b' => 'lim',
		'639-3' => 'lim',
		'iso_language_name' => 'Limburgish, Limburgan, Limburger',
		'native_name_(endonym)' => 'Limburgs',
	],
	[
		'639-1' => 'ln',
		'639-2/t' => 'lin',
		'639-2/b' => 'lin',
		'639-3' => 'lin',
		'iso_language_name' => 'Lingala',
		'native_name_(endonym)' => 'Lingála',
	],
	[
		'639-1' => 'lo',
		'639-2/t' => 'lao',
		'639-2/b' => 'lao',
		'639-3' => 'lao',
		'iso_language_name' => 'Lao',
		'native_name_(endonym)' => 'ພາສາລາວ',
	],
	[
		'639-1' => 'lt',
		'639-2/t' => 'lit',
		'639-2/b' => 'lit',
		'639-3' => 'lit',
		'iso_language_name' => 'Lithuanian',
		'native_name_(endonym)' => 'lietuvių kalba',
	],
	[
		'639-1' => 'lu',
		'639-2/t' => 'lub',
		'639-2/b' => 'lub',
		'639-3' => 'lub',
		'iso_language_name' => 'Luba-Katanga',
		'native_name_(endonym)' => 'Tshiluba',
	],
	[
		'639-1' => 'lv',
		'639-2/t' => 'lav',
		'639-2/b' => 'lav',
		'639-3' => 'lav',
		'iso_language_name' => 'Latvian',
		'native_name_(endonym)' => 'latviešu valoda',
	],
	[
		'639-1' => 'gv',
		'639-2/t' => 'glv',
		'639-2/b' => 'glv',
		'639-3' => 'glv',
		'iso_language_name' => 'Manx',
		'native_name_(endonym)' => 'Gaelg, Gailck',
	],
	[
		'639-1' => 'mk',
		'639-2/t' => 'mkd',
		'639-2/b' => 'mac',
		'639-3' => 'mkd',
		'iso_language_name' => 'Macedonian',
		'native_name_(endonym)' => 'македонски јазик',
	],
	[
		'639-1' => 'mg',
		'639-2/t' => 'mlg',
		'639-2/b' => 'mlg',
		'639-3' => 'mlg',
		'iso_language_name' => 'Malagasy',
		'native_name_(endonym)' => 'fiteny malagasy',
	],
	[
		'639-1' => 'ms',
		'639-2/t' => 'msa',
		'639-2/b' => 'may',
		'639-3' => 'msa',
		'iso_language_name' => 'Malay',
		'native_name_(endonym)' => 'bahasa Melayu, بهاس ملايو‎',
	],
	[
		'639-1' => 'ml',
		'639-2/t' => 'mal',
		'639-2/b' => 'mal',
		'639-3' => 'mal',
		'iso_language_name' => 'Malayalam',
		'native_name_(endonym)' => 'മലയാളം',
	],
	[
		'639-1' => 'mt',
		'639-2/t' => 'mlt',
		'639-2/b' => 'mlt',
		'639-3' => 'mlt',
		'iso_language_name' => 'Maltese',
		'native_name_(endonym)' => 'Malti',
	],
	[
		'639-1' => 'mi',
		'639-2/t' => 'mri',
		'639-2/b' => 'mao',
		'639-3' => 'mri',
		'iso_language_name' => 'Māori',
		'native_name_(endonym)' => 'te reo Māori',
	],
	[
		'639-1' => 'mr',
		'639-2/t' => 'mar',
		'639-2/b' => 'mar',
		'639-3' => 'mar',
		'iso_language_name' => 'Marathi (Marāṭhī)',
		'native_name_(endonym)' => 'मराठी',
	],
	[
		'639-1' => 'mh',
		'639-2/t' => 'mah',
		'639-2/b' => 'mah',
		'639-3' => 'mah',
		'iso_language_name' => 'Marshallese',
		'native_name_(endonym)' => 'Kajin M̧ajeļ',
	],
	[
		'639-1' => 'mn',
		'639-2/t' => 'mon',
		'639-2/b' => 'mon',
		'639-3' => 'mon',
		'iso_language_name' => 'Mongolian',
		'native_name_(endonym)' => 'монгол',
	],
	[
		'639-1' => 'na',
		'639-2/t' => 'nau',
		'639-2/b' => 'nau',
		'639-3' => 'nau',
		'iso_language_name' => 'Nauru',
		'native_name_(endonym)' => 'Ekakairũ Naoero',
	],
	[
		'639-1' => 'nv',
		'639-2/t' => 'nav',
		'639-2/b' => 'nav',
		'639-3' => 'nav',
		'iso_language_name' => 'Navajo, Navaho',
		'native_name_(endonym)' => 'Diné bizaad',
	],
	[
		'639-1' => 'nd',
		'639-2/t' => 'nde',
		'639-2/b' => 'nde',
		'639-3' => 'nde',
		'iso_language_name' => 'Northern Ndebele',
		'native_name_(endonym)' => 'isiNdebele',
	],
	[
		'639-1' => 'ne',
		'639-2/t' => 'nep',
		'639-2/b' => 'nep',
		'639-3' => 'nep',
		'iso_language_name' => 'Nepali',
		'native_name_(endonym)' => 'नेपाली',
	],
	[
		'639-1' => 'ng',
		'639-2/t' => 'ndo',
		'639-2/b' => 'ndo',
		'639-3' => 'ndo',
		'iso_language_name' => 'Ndonga',
		'native_name_(endonym)' => 'Owambo',
	],
	[
		'639-1' => 'nb',
		'639-2/t' => 'nob',
		'639-2/b' => 'nob',
		'639-3' => 'nob',
		'iso_language_name' => 'Norwegian Bokmål',
		'native_name_(endonym)' => 'Norsk bokmål',
	],
	[
		'639-1' => 'nn',
		'639-2/t' => 'nno',
		'639-2/b' => 'nno',
		'639-3' => 'nno',
		'iso_language_name' => 'Norwegian Nynorsk',
		'native_name_(endonym)' => 'Norsk nynorsk',
	],
	[
		'639-1' => 'no',
		'639-2/t' => 'nor',
		'639-2/b' => 'nor',
		'639-3' => 'nor',
		'iso_language_name' => 'Norwegian',
		'native_name_(endonym)' => 'Norsk',
	],
	[
		'639-1' => 'ii',
		'639-2/t' => 'iii',
		'639-2/b' => 'iii',
		'639-3' => 'iii',
		'iso_language_name' => 'Nuosu',
		'native_name_(endonym)' => 'ꆈꌠ꒿ Nuosuhxop',
	],
	[
		'639-1' => 'nr',
		'639-2/t' => 'nbl',
		'639-2/b' => 'nbl',
		'639-3' => 'nbl',
		'iso_language_name' => 'Southern Ndebele',
		'native_name_(endonym)' => 'isiNdebele',
	],
	[
		'639-1' => 'oc',
		'639-2/t' => 'oci',
		'639-2/b' => 'oci',
		'639-3' => 'oci',
		'iso_language_name' => 'Occitan',
		'native_name_(endonym)' => 'occitan, lenga d\'òc',
	],
	[
		'639-1' => 'oj',
		'639-2/t' => 'oji',
		'639-2/b' => 'oji',
		'639-3' => 'oji',
		'iso_language_name' => 'Ojibwe, Ojibwa',
		'native_name_(endonym)' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
	],
	[
		'639-1' => 'cu',
		'639-2/t' => 'chu',
		'639-2/b' => 'chu',
		'639-3' => 'chu',
		'iso_language_name' => 'Old Church Slavonic, Church Slavonic, Old Bulgarian',
		'native_name_(endonym)' => 'ѩзыкъ словѣньскъ',
	],
	[
		'639-1' => 'om',
		'639-2/t' => 'orm',
		'639-2/b' => 'orm',
		'639-3' => 'orm',
		'iso_language_name' => 'Oromo',
		'native_name_(endonym)' => 'Afaan Oromoo',
	],
	[
		'639-1' => 'or',
		'639-2/t' => 'ori',
		'639-2/b' => 'ori',
		'639-3' => 'ori',
		'iso_language_name' => 'Oriya',
		'native_name_(endonym)' => 'ଓଡ଼ିଆ',
	],
	[
		'639-1' => 'os',
		'639-2/t' => 'oss',
		'639-2/b' => 'oss',
		'639-3' => 'oss',
		'iso_language_name' => 'Ossetian, Ossetic',
		'native_name_(endonym)' => 'ирон æвзаг',
	],
	[
		'639-1' => 'pa',
		'639-2/t' => 'pan',
		'639-2/b' => 'pan',
		'639-3' => 'pan',
		'iso_language_name' => 'Panjabi, Punjabi',
		'native_name_(endonym)' => 'ਪੰਜਾਬੀ, پنجابی‎',
	],
	[
		'639-1' => 'pi',
		'639-2/t' => 'pli',
		'639-2/b' => 'pli',
		'639-3' => 'pli',
		'iso_language_name' => 'Pāli',
		'native_name_(endonym)' => 'पाऴि',
	],
	[
		'639-1' => 'fa',
		'639-2/t' => 'fas',
		'639-2/b' => 'per',
		'639-3' => 'fas',
		'iso_language_name' => 'Persian (Farsi)',
		'native_name_(endonym)' => 'فارسی',
	],
	[
		'639-1' => 'pl',
		'639-2/t' => 'pol',
		'639-2/b' => 'pol',
		'639-3' => 'pol',
		'iso_language_name' => 'Polish',
		'native_name_(endonym)' => 'język polski, polszczyzna',
	],
	[
		'639-1' => 'ps',
		'639-2/t' => 'pus',
		'639-2/b' => 'pus',
		'639-3' => 'pus',
		'iso_language_name' => 'Pashto, Pushto',
		'native_name_(endonym)' => 'پښتو',
	],
	[
		'639-1' => 'pt',
		'639-2/t' => 'por',
		'639-2/b' => 'por',
		'639-3' => 'por',
		'iso_language_name' => 'Portuguese',
		'native_name_(endonym)' => 'português',
	],
	[
		'639-1' => 'qu',
		'639-2/t' => 'que',
		'639-2/b' => 'que',
		'639-3' => 'que',
		'iso_language_name' => 'Quechua',
		'native_name_(endonym)' => 'Runa Simi, Kichwa',
	],
	[
		'639-1' => 'rm',
		'639-2/t' => 'roh',
		'639-2/b' => 'roh',
		'639-3' => 'roh',
		'iso_language_name' => 'Romansh',
		'native_name_(endonym)' => 'rumantsch grischun',
	],
	[
		'639-1' => 'rn',
		'639-2/t' => 'run',
		'639-2/b' => 'run',
		'639-3' => 'run',
		'iso_language_name' => 'Kirundi',
		'native_name_(endonym)' => 'Ikirundi',
	],
	[
		'639-1' => 'ro',
		'639-2/t' => 'ron',
		'639-2/b' => 'rum',
		'639-3' => 'ron',
		'iso_language_name' => 'Romanian',
		'native_name_(endonym)' => 'limba română',
	],
	[
		'639-1' => 'ru',
		'639-2/t' => 'rus',
		'639-2/b' => 'rus',
		'639-3' => 'rus',
		'iso_language_name' => 'Russian',
		'native_name_(endonym)' => 'Русский',
	],
	[
		'639-1' => 'sa',
		'639-2/t' => 'san',
		'639-2/b' => 'san',
		'639-3' => 'san',
		'iso_language_name' => 'Sanskrit (Saṁskṛta)',
		'native_name_(endonym)' => 'संस्कृतम्',
	],
	[
		'639-1' => 'sc',
		'639-2/t' => 'srd',
		'639-2/b' => 'srd',
		'639-3' => 'srd',
		'iso_language_name' => 'Sardinian',
		'native_name_(endonym)' => 'sardu',
	],
	[
		'639-1' => 'sd',
		'639-2/t' => 'snd',
		'639-2/b' => 'snd',
		'639-3' => 'snd',
		'iso_language_name' => 'Sindhi',
		'native_name_(endonym)' => 'सिन्धी, سنڌي، سندھی‎',
	],
	[
		'639-1' => 'se',
		'639-2/t' => 'sme',
		'639-2/b' => 'sme',
		'639-3' => 'sme',
		'iso_language_name' => 'Northern Sami',
		'native_name_(endonym)' => 'Davvisámegiella',
	],
	[
		'639-1' => 'sm',
		'639-2/t' => 'smo',
		'639-2/b' => 'smo',
		'639-3' => 'smo',
		'iso_language_name' => 'Samoan',
		'native_name_(endonym)' => 'gagana fa\'a Samoa',
	],
	[
		'639-1' => 'sg',
		'639-2/t' => 'sag',
		'639-2/b' => 'sag',
		'639-3' => 'sag',
		'iso_language_name' => 'Sango',
		'native_name_(endonym)' => 'yângâ tî sängö',
	],
	[
		'639-1' => 'sr',
		'639-2/t' => 'srp',
		'639-2/b' => 'srp',
		'639-3' => 'srp',
		'iso_language_name' => 'Serbian',
		'native_name_(endonym)' => 'српски језик',
	],
	[
		'639-1' => 'gd',
		'639-2/t' => 'gla',
		'639-2/b' => 'gla',
		'639-3' => 'gla',
		'iso_language_name' => 'Scottish Gaelic, Gaelic',
		'native_name_(endonym)' => 'Gàidhlig',
	],
	[
		'639-1' => 'sn',
		'639-2/t' => 'sna',
		'639-2/b' => 'sna',
		'639-3' => 'sna',
		'iso_language_name' => 'Shona',
		'native_name_(endonym)' => 'chiShona',
	],
	[
		'639-1' => 'si',
		'639-2/t' => 'sin',
		'639-2/b' => 'sin',
		'639-3' => 'sin',
		'iso_language_name' => 'Sinhala, Sinhalese',
		'native_name_(endonym)' => 'සිංහල',
	],
	[
		'639-1' => 'sk',
		'639-2/t' => 'slk',
		'639-2/b' => 'slo',
		'639-3' => 'slk',
		'iso_language_name' => 'Slovak',
		'native_name_(endonym)' => 'slovenčina, slovenský jazyk',
	],
	[
		'639-1' => 'sl',
		'639-2/t' => 'slv',
		'639-2/b' => 'slv',
		'639-3' => 'slv',
		'iso_language_name' => 'Slovene',
		'native_name_(endonym)' => 'slovenski jezik, slovenščina',
	],
	[
		'639-1' => 'so',
		'639-2/t' => 'som',
		'639-2/b' => 'som',
		'639-3' => 'som',
		'iso_language_name' => 'Somali',
		'native_name_(endonym)' => 'Soomaaliga, af Soomaali',
	],
	[
		'639-1' => 'st',
		'639-2/t' => 'sot',
		'639-2/b' => 'sot',
		'639-3' => 'sot',
		'iso_language_name' => 'Southern Sotho',
		'native_name_(endonym)' => 'Sesotho',
	],
	[
		'639-1' => 'es',
		'639-2/t' => 'spa',
		'639-2/b' => 'spa',
		'639-3' => 'spa',
		'iso_language_name' => 'Spanish',
		'native_name_(endonym)' => 'español',
	],
	[
		'639-1' => 'su',
		'639-2/t' => 'sun',
		'639-2/b' => 'sun',
		'639-3' => 'sun',
		'iso_language_name' => 'Sundanese',
		'native_name_(endonym)' => 'Basa Sunda',
	],
	[
		'639-1' => 'sw',
		'639-2/t' => 'swa',
		'639-2/b' => 'swa',
		'639-3' => 'swa',
		'iso_language_name' => 'Swahili',
		'native_name_(endonym)' => 'Kiswahili',
	],
	[
		'639-1' => 'ss',
		'639-2/t' => 'ssw',
		'639-2/b' => 'ssw',
		'639-3' => 'ssw',
		'iso_language_name' => 'Swati',
		'native_name_(endonym)' => 'SiSwati',
	],
	[
		'639-1' => 'sv',
		'639-2/t' => 'swe',
		'639-2/b' => 'swe',
		'639-3' => 'swe',
		'iso_language_name' => 'Swedish',
		'native_name_(endonym)' => 'svenska',
	],
	[
		'639-1' => 'ta',
		'639-2/t' => 'tam',
		'639-2/b' => 'tam',
		'639-3' => 'tam',
		'iso_language_name' => 'Tamil',
		'native_name_(endonym)' => 'தமிழ்',
	],
	[
		'639-1' => 'te',
		'639-2/t' => 'tel',
		'639-2/b' => 'tel',
		'639-3' => 'tel',
		'iso_language_name' => 'Telugu',
		'native_name_(endonym)' => 'తెలుగు',
	],
	[
		'639-1' => 'tg',
		'639-2/t' => 'tgk',
		'639-2/b' => 'tgk',
		'639-3' => 'tgk',
		'iso_language_name' => 'Tajik',
		'native_name_(endonym)' => 'тоҷикӣ, toçikī, تاجیکی‎',
	],
	[
		'639-1' => 'th',
		'639-2/t' => 'tha',
		'639-2/b' => 'tha',
		'639-3' => 'tha',
		'iso_language_name' => 'Thai',
		'native_name_(endonym)' => 'ไทย',
	],
	[
		'639-1' => 'ti',
		'639-2/t' => 'tir',
		'639-2/b' => 'tir',
		'639-3' => 'tir',
		'iso_language_name' => 'Tigrinya',
		'native_name_(endonym)' => 'ትግርኛ',
	],
	[
		'639-1' => 'bo',
		'639-2/t' => 'bod',
		'639-2/b' => 'tib',
		'639-3' => 'bod',
		'iso_language_name' => 'Tibetan Standard, Tibetan, Central',
		'native_name_(endonym)' => 'བོད་ཡིག',
	],
	[
		'639-1' => 'tk',
		'639-2/t' => 'tuk',
		'639-2/b' => 'tuk',
		'639-3' => 'tuk',
		'iso_language_name' => 'Turkmen',
		'native_name_(endonym)' => 'Türkmen, Түркмен',
	],
	[
		'639-1' => 'tl',
		'639-2/t' => 'tgl',
		'639-2/b' => 'tgl',
		'639-3' => 'tgl',
		'iso_language_name' => 'Tagalog',
		'native_name_(endonym)' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔',
	],
	[
		'639-1' => 'tn',
		'639-2/t' => 'tsn',
		'639-2/b' => 'tsn',
		'639-3' => 'tsn',
		'iso_language_name' => 'Tswana',
		'native_name_(endonym)' => 'Setswana',
	],
	[
		'639-1' => 'to',
		'639-2/t' => 'ton',
		'639-2/b' => 'ton',
		'639-3' => 'ton',
		'iso_language_name' => 'Tonga (Tonga Islands)',
		'native_name_(endonym)' => 'faka Tonga',
	],
	[
		'639-1' => 'tr',
		'639-2/t' => 'tur',
		'639-2/b' => 'tur',
		'639-3' => 'tur',
		'iso_language_name' => 'Turkish',
		'native_name_(endonym)' => 'Türkçe',
	],
	[
		'639-1' => 'ts',
		'639-2/t' => 'tso',
		'639-2/b' => 'tso',
		'639-3' => 'tso',
		'iso_language_name' => 'Tsonga',
		'native_name_(endonym)' => 'Xitsonga',
	],
	[
		'639-1' => 'tt',
		'639-2/t' => 'tat',
		'639-2/b' => 'tat',
		'639-3' => 'tat',
		'iso_language_name' => 'Tatar',
		'native_name_(endonym)' => 'татар теле, tatar tele',
	],
	[
		'639-1' => 'tw',
		'639-2/t' => 'twi',
		'639-2/b' => 'twi',
		'639-3' => 'twi',
		'iso_language_name' => 'Twi',
		'native_name_(endonym)' => 'Twi',
	],
	[
		'639-1' => 'ty',
		'639-2/t' => 'tah',
		'639-2/b' => 'tah',
		'639-3' => 'tah',
		'iso_language_name' => 'Tahitian',
		'native_name_(endonym)' => 'Reo Tahiti',
	],
	[
		'639-1' => 'ug',
		'639-2/t' => 'uig',
		'639-2/b' => 'uig',
		'639-3' => 'uig',
		'iso_language_name' => 'Uyghur',
		'native_name_(endonym)' => 'ئۇيغۇرچە‎, Uyghurche',
	],
	[
		'639-1' => 'uk',
		'639-2/t' => 'ukr',
		'639-2/b' => 'ukr',
		'639-3' => 'ukr',
		'iso_language_name' => 'Ukrainian',
		'native_name_(endonym)' => 'українська мова',
	],
	[
		'639-1' => 'ur',
		'639-2/t' => 'urd',
		'639-2/b' => 'urd',
		'639-3' => 'urd',
		'iso_language_name' => 'Urdu',
		'native_name_(endonym)' => 'اردو',
	],
	[
		'639-1' => 'uz',
		'639-2/t' => 'uzb',
		'639-2/b' => 'uzb',
		'639-3' => 'uzb',
		'iso_language_name' => 'Uzbek',
		'native_name_(endonym)' => 'Oʻzbek, Ўзбек, أۇزبېك‎',
	],
	[
		'639-1' => 've',
		'639-2/t' => 'ven',
		'639-2/b' => 'ven',
		'639-3' => 'ven',
		'iso_language_name' => 'Venda',
		'native_name_(endonym)' => 'Tshivenḓa',
	],
	[
		'639-1' => 'vi',
		'639-2/t' => 'vie',
		'639-2/b' => 'vie',
		'639-3' => 'vie',
		'iso_language_name' => 'Vietnamese',
		'native_name_(endonym)' => 'Việt Nam',
	],
	[
		'639-1' => 'vo',
		'639-2/t' => 'vol',
		'639-2/b' => 'vol',
		'639-3' => 'vol',
		'iso_language_name' => 'Volapük',
		'native_name_(endonym)' => 'Volapük',
	],
	[
		'639-1' => 'wa',
		'639-2/t' => 'wln',
		'639-2/b' => 'wln',
		'639-3' => 'wln',
		'iso_language_name' => 'Walloon',
		'native_name_(endonym)' => 'walon',
	],
	[
		'639-1' => 'cy',
		'639-2/t' => 'cym',
		'639-2/b' => 'wel',
		'639-3' => 'cym',
		'iso_language_name' => 'Welsh',
		'native_name_(endonym)' => 'Cymraeg',
	],
	[
		'639-1' => 'wo',
		'639-2/t' => 'wol',
		'639-2/b' => 'wol',
		'639-3' => 'wol',
		'iso_language_name' => 'Wolof',
		'native_name_(endonym)' => 'Wollof',
	],
	[
		'639-1' => 'fy',
		'639-2/t' => 'fry',
		'639-2/b' => 'fry',
		'639-3' => 'fry',
		'iso_language_name' => 'Western Frisian',
		'native_name_(endonym)' => 'Frysk',
	],
	[
		'639-1' => 'xh',
		'639-2/t' => 'xho',
		'639-2/b' => 'xho',
		'639-3' => 'xho',
		'iso_language_name' => 'Xhosa',
		'native_name_(endonym)' => 'isiXhosa',
	],
	[
		'639-1' => 'yi',
		'639-2/t' => 'yid',
		'639-2/b' => 'yid',
		'639-3' => 'yid',
		'iso_language_name' => 'Yiddish',
		'native_name_(endonym)' => 'ייִדיש',
	],
	[
		'639-1' => 'yo',
		'639-2/t' => 'yor',
		'639-2/b' => 'yor',
		'639-3' => 'yor',
		'iso_language_name' => 'Yoruba',
		'native_name_(endonym)' => 'Yorùbá',
	],
	[
		'639-1' => 'za',
		'639-2/t' => 'zha',
		'639-2/b' => 'zha',
		'639-3' => 'zha',
		'iso_language_name' => 'Zhuang, Chuang',
		'native_name_(endonym)' => 'Saɯ cueŋƅ, Saw cuengh',
	],
	[
		'639-1' => 'zu',
		'639-2/t' => 'zul',
		'639-2/b' => 'zul',
		'639-3' => 'zul',
		'iso_language_name' => 'Zulu',
		'native_name_(endonym)' => 'isiZulu',
	],
];